export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const COMPILE_REQUEST = 'COMPILE_REQUEST'
export const COMPILE_SUCCESS = 'COMPILE_SUCCESS'
export const COMPILE_FAILURE = 'COMPILE_FAILURE'